export interface BibleBook {
    id: number;
    name: string;
    chapters: number;
    category: 'Old' | 'New';
}

export const BIBLE_BOOKS: BibleBook[] = [
    { id: 1, name: "창세기", chapters: 50, category: "Old" },
    { id: 2, name: "출애굽기", chapters: 40, category: "Old" },
    { id: 3, name: "레위기", chapters: 27, category: "Old" },
    { id: 4, name: "민수기", chapters: 36, category: "Old" },
    { id: 5, name: "신명기", chapters: 34, category: "Old" },
    { id: 6, name: "여호수아", chapters: 24, category: "Old" },
    { id: 7, name: "사사기", chapters: 21, category: "Old" },
    { id: 8, name: "룻기", chapters: 4, category: "Old" },
    { id: 9, name: "사무엘상", chapters: 31, category: "Old" },
    { id: 10, name: "사무엘하", chapters: 24, category: "Old" },
    { id: 11, name: "열왕기상", chapters: 22, category: "Old" },
    { id: 12, name: "열왕기하", chapters: 25, category: "Old" },
    { id: 13, name: "역대상", chapters: 29, category: "Old" },
    { id: 14, name: "역대하", chapters: 36, category: "Old" },
    { id: 15, name: "에스라", chapters: 10, category: "Old" },
    { id: 16, name: "느헤미야", chapters: 13, category: "Old" },
    { id: 17, name: "에스더", chapters: 10, category: "Old" },
    { id: 18, name: "욥기", chapters: 42, category: "Old" },
    { id: 19, name: "시편", chapters: 150, category: "Old" },
    { id: 20, name: "잠언", chapters: 31, category: "Old" },
    { id: 21, name: "전도서", chapters: 12, category: "Old" },
    { id: 22, name: "아가", chapters: 8, category: "Old" },
    { id: 23, name: "이사야", chapters: 66, category: "Old" },
    { id: 24, name: "예레미야", chapters: 52, category: "Old" },
    { id: 25, name: "예레미야 애가", chapters: 5, category: "Old" },
    { id: 26, name: "에스겔", chapters: 48, category: "Old" },
    { id: 27, name: "다니엘", chapters: 12, category: "Old" },
    { id: 28, name: "호세아", chapters: 14, category: "Old" },
    { id: 29, name: "요엘", chapters: 3, category: "Old" },
    { id: 30, name: "아모스", chapters: 9, category: "Old" },
    { id: 31, name: "오바디야", chapters: 1, category: "Old" },
    { id: 32, name: "요나", chapters: 4, category: "Old" },
    { id: 33, name: "미가", chapters: 7, category: "Old" },
    { id: 34, name: "나훔", chapters: 3, category: "Old" },
    { id: 35, name: "하박국", chapters: 3, category: "Old" },
    { id: 36, name: "스바냐", chapters: 3, category: "Old" },
    { id: 37, name: "학개", chapters: 2, category: "Old" },
    { id: 38, name: "스가랴", chapters: 14, category: "Old" },
    { id: 39, name: "말라기", chapters: 4, category: "Old" },
    { id: 40, name: "마태복음", chapters: 28, category: "New" },
    { id: 41, name: "마가복음", chapters: 16, category: "New" },
    { id: 42, name: "누가복음", chapters: 24, category: "New" },
    { id: 43, name: "요한복음", chapters: 21, category: "New" },
    { id: 44, name: "사도행전", chapters: 28, category: "New" },
    { id: 45, name: "로마서", chapters: 16, category: "New" },
    { id: 46, name: "고린도전서", chapters: 16, category: "New" },
    { id: 47, name: "고린도후서", chapters: 13, category: "New" },
    { id: 48, name: "갈라디아서", chapters: 6, category: "New" },
    { id: 49, name: "에베소서", chapters: 6, category: "New" },
    { id: 50, name: "빌립보서", chapters: 4, category: "New" },
    { id: 51, name: "골로새서", chapters: 4, category: "New" },
    { id: 52, name: "데살로니가전서", chapters: 5, category: "New" },
    { id: 53, name: "데살로니가후서", chapters: 3, category: "New" },
    { id: 54, name: "디모데전서", chapters: 6, category: "New" },
    { id: 55, name: "디모데후서", chapters: 4, category: "New" },
    { id: 56, name: "디도서", chapters: 3, category: "New" },
    { id: 57, name: "빌레몬서", chapters: 1, category: "New" },
    { id: 58, name: "히브리서", chapters: 13, category: "New" },
    { id: 59, name: "야고보서", chapters: 5, category: "New" },
    { id: 60, name: "베드로전서", chapters: 5, category: "New" },
    { id: 61, name: "베드로후서", chapters: 3, category: "New" },
    { id: 62, name: "요한일서", chapters: 5, category: "New" },
    { id: 63, name: "요한이서", chapters: 1, category: "New" },
    { id: 64, name: "요한삼서", chapters: 1, category: "New" },
    { id: 65, name: "유다서", chapters: 1, category: "New" },
    { id: 66, name: "요한계시록", chapters: 22, category: "New" },
];

export const TOTAL_CHAPTERS = BIBLE_BOOKS.reduce((acc, book) => acc + book.chapters, 0);
